# Generated by Django 3.1.3 on 2021-02-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.CharField(default='gg', max_length=300)),
                ('full_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
