# Generated by Django 3.1.3 on 2021-02-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedlinks',
            name='full_link',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='generatedlinks',
            name='short_link',
            field=models.CharField(default='gg', max_length=300, unique=True),
        ),
    ]
